### ISSUE TITLE
Speech-to-text functionality

### ISSUE THREAD

**Issue by holwech** [holwech/incrementally-backend#10]
#### User story
As an educator, I want the things I say to be transcribed, so that viewers can read what's being said in a video

#### Tasks
- [ ] - Convert voice recording to text with Azure API
- [ ] - Access voice file and pass it to API
- [ ] - Store speech-to-text file in Azure storage

#### Related tasks
- incrementallygroup/incrementally-backend#9
